kind: Service
apiVersion: v1

metadata:
    name: node-app-service
    namespace: node-app-namespace
spec:
    type: NodePort
    selector:
        app: node-app-labels
    ports:
       - port: 5000
         targetPort: 5000
         nodePort: 30007