# name: setup-and-greet

# inputs:
#   name:
#     required: true
#     type: string

#   language:
#     required: false
#     type: string
#     default: en

# outputs:
#   greeted:
#     value: ${{ steps.output-step.outputs.greeted }}

# runs:
#   using: "composite"
#   steps:
#     - name: print inputs
#       shell: bash
#       run: |
#         echo "Language: ${{ inputs.language }}"
#         echo "Name: ${{ inputs.name }}"

#     - name: print system info
#       shell: bash
#       run: |
#         echo "Date: $(date)"
#         echo "OS: $RUNNER_OS"

#     - name: set output
#       id: output-step
#       shell: bash
#       run: |
#         echo "greeted=true" >> $GITHUB_OUTPUT