name: call-build

on: 
    push:
        branches: 
            - master

jobs:
    resuable:
        uses: ./.github/workflows/reusable.yml
        with:
            app_name: "webu"
            environment: "production"
        secrets:
            docker_token: ${{ secrets.DOCKER_TOKEN }}

        