name: call-build

on:
  push:
    branches:
      - main

jobs:
  call-build:
    uses: ./.github/workflows/reusable.yml
    with:
      app_name: "webu"
      environment: "production"
    secrets:
      docker_token: ${{ secrets.DOCKER_TOKEN }}

  print-version:
    runs-on: ubuntu-latest
    needs: call-build

    steps:
      - name: print version
        run: echo "Build version is ${{ needs.call-build.outputs.build_version }}"