name: use composite

on: 
    push:
        branches:
            - master

jobs:
    tests:
        runs-on: ubuntu
        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: run costom greet
              id: greet
              uses: ./.github/actions/setup-and-greet
              with:
                name: "Sahil"
                langauge: "Punjabi"

            - name: checkout output
              run: |
                echo "Greeted: ${{ steps.greet.outputs.greeted }}"