name: deploy

on: 
    workflow_dispatch:

jobs:
    deploying:
        runs-on: self-hosted
        env:
           DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER }}
           DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
           DOCKERHUB_TAG: ${{ github.sha }}
        steps:
            - name: check out code
              uses: actions/checkout@v4
              
            - name: set up docker compose 
              uses: docker/setup-compose-action@v2

            - name: deploy with docker compose 
              run: docker compose down && docker compose up -d --build --force-recreate