name: pr-checks

on:
    pull_request:
        types: [opened , synchronize , reopened , closed]
        branches:
            - master

jobs:
    file-size-check:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            
            - name: Check file sizes in PR
              run: |
                 echo "Checking files larger than 1 MB..."
                  git fetch origin ${{ github.base_ref }}
                  FILES=$(git diff --name-only --diff-filter=AM origin/${{ github.base_ref }})
                   LIMIT=$((1024 * 1024)) # 1 MB
                   FAIL=0

                 for file in $FILES; do
                    if [ -f "$file" ]; then
                    SIZE=$(stat -c%s "$file")
                    echo "$file => $SIZE bytes"

                    if [ "$SIZE" -gt "$LIMIT" ]; then
                        echo "❌ $file exceeds 1 MB limit"
                        FAIL=1
                    fi
                    fi
                 done

                 if [ "$FAIL" -eq 1 ]; then
                    echo "🚨 File size check failed"
                    exit 1
                 else
                    echo "✅ All files are within limit"
                 fi
    branch-name-check:
        runs-on: ubuntu-latest
        env:
            branch: ${{ github.ref_name }}
        steps:
            - name: check pattern
              run: |
                BRANCH_NAME="${{ github.ref_name }}"
                echo "checking pattern: $BRANCH_NAME"
                if [[ "$BRANCH_NAME" =~ ^(feature|fix|docs)/.+$ ]]; then
                    echo "branch name valid"
                else
                    echo "not valid branch"
                    exit 1
                fi
