name: pull request lifecycle

on:
    pull_request:
        types: [opened , reopened, synchronize , closed]
        branches:
            - main
jobs:
    events:
        runs-on: ubuntu-latest
        steps:
            - name: event fired , pr title , pr author 
              run: |
                 echo "${{ github.event.action }}"
                 echo "${{ github.event.pull_request.title }}"
                 echo "${{ github.event.pull_request.user.login }}"

            - name: pr merge or not
              if: ${{ github.event.pull_request.merged == true }}
              run: |
                  echo "Bai pr merge hogi aa"