name: resuable-build

on: 
    workflow_call:
        inputs:
            app_name:
                type: string
                default: "noduuu"
                required: true
            environment:
                type: string
                default: 'staging'
                required: true
env:
    SECRETS : ${{secrets.DOCKERHUB_TOKEN}}
jobs:
    reusable:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: checkout/actions@v4
            
            - name: Building
              run: echo "Building ${{ github.event.inputs.app_name }} for ${{ github.event.inputs.environment }} env"
            
            - name: Token checker
              run: |
                 if [ -z "${SECRETS}" ]; then
                     echo "SECRETS is NOT set"
                     exit 1
                 else
                     echo "SECRETS is set"
                 fi
       