name: resuable-build

on: 
    workflow_call:
        inputs:
            app_name:
                type: string
                required: true
            environment:
                type: string
                default: 'staging'
                required: true
        outputs:
            build_version:
                 value: ${{ jobs.reusable.outputs.build_version }}
env:
    SECRETS : ${docker_token}
jobs:
    reusable:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4

            - name: generate version
              id: version
              run: |
                   VERSION="v1.0-$(git rev-parse --short HEAD)"
                   echo "build_version=$VERSION" >> $GITHUB_OUTPUT

            - name: Building
              run: echo "Building ${{ inputs.app_name }} for ${{ inputs.environment }} env"
            
            - name: Token checker
              run: |
                 if [ -z "${SECRETS}" ]; then
                     echo "SECRETS is NOT set"
                     exit 1
                 else
                     echo "SECRETS is set"
                 fi
       